### ISSUE TITLE
-h hosts.txt TypeError

### ISSUE THREAD

**Issue by deadwind4** [lilydjwg/pssh#109]
Input command  pssh -h hosts.txt -i uptime

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/pssh", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/wolf/github-work/pssh/bin/pssh", line 109, in <module>
    default_user=opts.user)
  File "/Users/wolf/github-work/pssh/psshlib/psshutil.py", line 20, in read_host_files
    hosts.extend(read_host_file(path, host_glob, default_user=default_user))
  File "/Users/wolf/github-work/pssh/psshlib/psshutil.py", line 44, in read_host_file
    host, port, user = parse_host_entry(line, default_user, default_port, host_glob)
TypeError: parse_host_entry() takes 3 positional arguments but 4 were given

Function parse_host_entry has an extra parameter in psshutil.py 44 line. Thus it leads to wrong reporting。

**Comment by lilydjwg** [comment]
Fixed, thanks!
