### ISSUE TITLE
ssh2.exceptions.PublickeyUnverifiedError

### ISSUE THREAD

**Issue by max-l** [lilydjwg/pssh#134]
I have have an rsa key that works the ssh program running from a shell (ssh -i myKey me@myhost)

When connecting with pssh, I get this exception: 

```
Traceback (most recent call last):
  File "/home/maxou/dev/dry_pipe/venv3.10/lib/python3.10/site-packages/pssh/clients/base/single.py", line 204, in _auth_retry
    self.auth()
  File "/home/maxou/dev/dry_pipe/venv3.10/lib/python3.10/site-packages/pssh/clients/base/single.py", line 349, in auth
    return self._pkey_auth(self.pkey)
  File "/home/maxou/dev/dry_pipe/venv3.10/lib/python3.10/site-packages/pssh/clients/base/single.py", line 389, in _pkey_auth
    return self._pkey_from_memory(_pkey)
  File "/home/maxou/dev/dry_pipe/venv3.10/lib/python3.10/site-packages/pssh/clients/native/single.py", line 255, in _pkey_from_memory
    self.session.userauth_publickey_frommemory(
  File "ssh2/session.pyx", line 293, in ssh2.session.Session.userauth_publickey_frommemory
  File "ssh2/utils.pyx", line 168, in ssh2.utils.handle_error_codes
ssh2.exceptions.PublickeyUnverifiedError
```

I have also tried with an id_ed25519 key, I get the same exception

Note1:  the same keys DO work when using pssh *on OTHER hosts*. So the problem is only with a specific host.

Node2: ssh -v gives me the same relevant lines, on working hosts as well as on non working hosts  : 

debug1: Local version string SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: compat_banner: match: OpenSSH_7.4 pat OpenSSH_7.4* compat 0x04000006

**Comment by lilydjwg** [comment]
You seem to have found the wrong project. No mentioned files exist in this project and this project doesn't use ssh2; it uses the `ssh` command line tool.
