### ISSUE TITLE
pssh for Windows OS

### ISSUE THREAD

**Issue by phillip-from-oz** [lilydjwg/pssh#144]
Is it possible to run pssh under Windows OS?

I have python3 installed installed on my Windows 10:
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

Questions
=======
1. Could I install this as:
In powershell, python3 -m pip pssh
2. What pre-requisites are required?
    I'm using putty as my ssh program
3. What changes would be required?

Thanks for any help

**Comment by lilydjwg** [comment]
You'll need openssh. Putty is not supported (it's a GUI thing anyway). Run `ssh -V` to check and make sure you can use the `ssh` command to login into your servers.

To install this project, you need to clone this repository (or download as a zip file) and run `pip install .` in the directory.

**Comment by phillip-from-oz** [comment]
1. I installed open SSH and tested that I can ssh to my servers
2.  installed pssh using the instructions provided
3. Run
python3 pssh
ModuleNotFoundError: No module named 'fcntl'

Apparently there is not fcntl module for Windows

**Comment by lilydjwg** [comment]
Retry latest master. Those `fcntl` calls are removed.

**Comment by phillip-from-oz** [comment]
Thanks for your quick response.

module 'os' has no attribute 'pipe2'

trace:
python3 pssh -A -i -H "TRAK-TRAIN01" echo "abc"
Traceback (most recent call last):
  File "C:\p\pssh-python\bin\pssh", line 119, in <module>
    do_pssh(hosts, cmdline, opts)
  File "C:\p\pssh-python\bin\pssh", line 75, in do_pssh
    manager = Manager(opts)
  File "C:\p\pssh-python\psshlib\manager.py", line 38, in __init__
    self.iomap = make_iomap()
  File "C:\p\pssh-python\psshlib\manager.py", line 301, in make_iomap
    return IOMap()
  File "C:\p\pssh-python\psshlib\manager.py", line 188, in __init__
    wakeup_readfd, wakeup_writefd = os.pipe2(os.O_NONBLOCK)
AttributeError: module 'os' has no attribute 'pipe2'. Did you mean: 'pipe'?

**Comment by lilydjwg** [comment]
OK, there are some SIGCHLD-related code, and I don't know how to do the same thing on Windows. So no, Windows is not supported.

**Comment by gch1p** [comment]
Also crashes on macOS:

```
Traceback (most recent call last):
  File "/Users/evgeny/Library/Python/3.13/bin/pssh", line 119, in <module>
    do_pssh(hosts, cmdline, opts)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evgeny/Library/Python/3.13/bin/pssh", line 75, in do_pssh
    manager = Manager(opts)
  File "/Users/evgeny/Library/Python/3.13/lib/python/site-packages/psshlib/manager.py", line 38, in __init__
    self.iomap = make_iomap()
                 ~~~~~~~~~~^^
  File "/Users/evgeny/Library/Python/3.13/lib/python/site-packages/psshlib/manager.py", line 299, in make_iomap
    return PollIOMap()
  File "/Users/evgeny/Library/Python/3.13/lib/python/site-packages/psshlib/manager.py", line 253, in __init__
    super(PollIOMap, self).__init__()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/evgeny/Library/Python/3.13/lib/python/site-packages/psshlib/manager.py", line 188, in __init__
    wakeup_readfd, wakeup_writefd = os.pipe2(os.O_NONBLOCK)
                                    ^^^^^^^^
AttributeError: module 'os' has no attribute 'pipe2'. Did you mean: 'pipe'?
```

**Comment by lilydjwg** [comment]
Weird, [the doc](https://docs.python.org/3/library/os.html#os.pipe2) says pipe2 is available on Unix. I've reverted the change however. Could you try again?

**Comment by gch1p** [comment]
Works just fine now!

**Comment by gch1p** [comment]
It seems `pipe2` syscall is implemented in Linux and FreeBSD (at least) but not in Darwin.
