### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lilydjwg/pssh#71]
```
What steps will reproduce the problem?
1. Create $TEMPFILE with a list of hosts
2. parallel-ssh -h $TEMPFILE -t -1 -o ${LOG_DIR} sudo -u ${USER} 
/home/${USER}/scripts/online.sh &

What is the expected output? What do you see instead?
Traceback (most recent call last):
  File "/usr/bin/parallel-ssh", line 115, in <module>
    do_pssh(hosts, cmdline, opts)
  File "/usr/bin/parallel-ssh", line 90, in do_pssh
    if min(statuses) < 0:
ValueError: min() arg is an empty sequence

What version of the product are you using? On what operating system?
2.2.2-0ubuntu1 on LinuxMint12

Please provide any additional information below.
I have attached a patch with a try-except block around the failing if statement.
```

Original issue reported on code.google.com by `andreas....@gmail.com` on 29 May 2012 at 7:31

Attachments:
- [pssh.patch](https://storage.googleapis.com/google-code-attachments/parallel-ssh/issue-71/comment-0/pssh.patch)

**Comment by compwron** [comment]
Is this fixed? I just installed from source and I am seeing this error. 

```git clone git@github.com:lilydjwg/pssh.git
cd pssh
python setup.py install
```

```Traceback (most recent call last):
  File "/usr/local/bin/pssh", line 4, in <module>
    __import__('pkg_resources').run_script('pssh==2.3.1', 'pssh')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/pssh-2.3.1-py2.7.egg/EGG-INFO/scripts/pssh", line 117, in <module>
    
  File "/usr/local/lib/python2.7/site-packages/pssh-2.3.1-py2.7.egg/EGG-INFO/scripts/pssh", line 96, in do_pssh
    
ValueError: min() arg is an empty sequence```
